version: '2'
services:
  db:
    image: mysql:8.0.25
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $DATABASE_PASSWORD
      MYSQL_DATABASE: $DATABASE_NAME
    volumes:
      - collabcode-db-config:/etc/mysql
      - collabcode-db-data:/var/lib/mysql
    ports:
      - $MYSQL_LOCAL_PORT:3306
  backend:
    env_file: ./.env
    build:
      context: .
      dockerfile: ./Dockerfile
    image: collabcode-backend
    ports:
      - $PORT:8080
    depends_on:
      - db
volumes:
  collabcode-db-config:
  collabcode-db-data:
